// AUTO-GENERATED by train.py --export-js. Runs the trained tree in the browser (edge inference).
const MOTION_LABELS = ["standing", "walking", "stumble"];
function motionFeatures(w) {
  const mean = (a) => a.reduce((p, c) => p + c, 0) / a.length;
  const sd = (a) => { const u = mean(a); return Math.sqrt(mean(a.map((v) => (v - u) ** 2))); };
  const m = w.map((s) => Math.hypot(s.x, s.y, s.z));
  const mn = Math.min(...m), mx = Math.max(...m);
  return { mag_mean: mean(m), mag_std: sd(m), mag_min: mn, mag_max: mx, mag_ptp: mx - mn,
    energy: mean(m.map((v) => v * v)), ax_std: sd(w.map((s) => s.x)), ay_std: sd(w.map((s) => s.y)), az_std: sd(w.map((s) => s.z)) };
}
function classifyMotion(samples) { // samples: 50 x {x,y,z} in g -> "standing" | "walking" | "stumble"
  const f = motionFeatures(samples);
  const c = (() => {
        if (f.mag_max <= 1.090004563331604) {
            if (f.energy <= 0.9915416240692139) {
                return 1;
            } else {
                return 0;
            }
        } else {
            if (f.mag_mean <= 1.0970352292060852) {
                if (f.mag_min <= 0.36330699920654297) {
                    return 2;
                } else {
                    if (f.ay_std <= 0.16232512891292572) {
                        return 1;
                    } else {
                        return 1;
                    }
                }
            } else {
                if (f.mag_max <= 2.5377397537231445) {
                    if (f.ax_std <= 0.19127246737480164) {
                        return 2;
                    } else {
                        return 1;
                    }
                } else {
                    return 2;
                }
            }
        }
  })();
  return MOTION_LABELS[c];
}
if (typeof module !== 'undefined') module.exports = { classifyMotion, motionFeatures };
